### PR TITLE
Remove Feedback

### LINKED ISSUE #10: Remove Submit Feedback page
# Remove Submit Feedback page 

* Removing files:
    * FeedbackViewModel
    * FeedbackView
* Remove category from `MainViewModel.categories`
* Remove code in `MainView` which opens `FeedbackView`
* Remove `feedback` image from `Assets`
* Remove Applysis SDK from package dependencies
* Remove import from `AppDelegate`

### PR DESCRIPTION
**Pull request by georgemakadze**
closes https://github.com/ashalva/ios.memenator/issues/10

1. Removing files:
- FeedbackViewModel
- FeedbackView

2. Remove category from MainViewModel.categories
3.  Remove code in MainView which opens FeedbackView
4. Remove feedback image from Assets
5. Remove Applysis SDK from package dependencies
6.  Remove import from AppDelegate

### CODE REVIEW

**Comment by ashalva** [comment]
@georgemakadze 

1. Please add your issue link to pull request description.
2. Please add me and @qetiavanashvili as reviewers.
3. Please add yourself only to assignees.

**Comment by georgemakadze** [comment]
@ashalva I corrected the entries that you wrote to me. Please check

**Review by ashalva — COMMENTED** [review]
Looks good, nice job 👏  
its ready to merge but we need to resolve the conflicts at first. Lets resolve the conflicts together with @qetiavanashvili 👍

**Comment by georgemakadze** [comment]
@ashalva  Thank you!

**Review by ashalva — APPROVED** [review]
Thanks for resolving conflicts 🙏

**Pull request merged**
